declare const useNotificationSettingDetail: () => {
    navItems: import("vue").ComputedRef<NavItem<NotificationSetting>[]>;
    activeId: import("vue").ComputedRef<string>;
    showActionsToggleTooltip: import("vue").Ref<boolean, boolean>;
    navLoading: import("vue").Ref<boolean, boolean>;
    onNavSelect: (id: string) => Promise<void>;
    tabs: import("vue").ComputedRef<{
        title: string;
        disabled: boolean;
        id: string;
        subtitle?: string;
        data?: any;
        icon?: Icon;
        iconSpinning?: boolean;
        tooltip?: string;
        emphasis?: boolean;
        style?: any;
        badge?: string | number;
        badgeType?: BasicType;
        label?: string;
        value?: any;
        children?: NavItem<any>[] | undefined;
        path?: string;
        level?: number;
    }[]>;
    activeTabName: import("vue").ComputedRef<string>;
    getForm: () => Promise<any>;
    onNavTabsSelect: (tabName: string) => Promise<void>;
    onBack: () => Promise<void>;
    onSave: () => Promise<void>;
};
export default useNotificationSettingDetail;
