api:
  address: "localhost:8000"
mongo:
  host: "192.168.235.26"
  port: 27017
  db: crawlab_dev
  username: "root"
  password: "example"
  authSource: "admin"
redis:
  address: 127.0.0.1
  password:
  database: 1
  port: 6379
log:
  level: info
  path: "./logs/crawlab"
  isDeletePeriodically: "N"
  deleteFrequency: "@hourly"
server:
  host: 0.0.0.0
  port: 8001
  master: "Y"
  secret: "crawlab"
  register:
    # mac地址 或者 ip地址，如果是ip，则需要手动指定IP
    type: "mac"
    ip: ""
  lang: # 安装语言环境, Y 为安装，N 为不安装，只对 Docker 有效
    python: "Y"
    node: "N"
spider:
  path: "./spiders"
task:
  workers: 4
other:
  tmppath: "./tmp"
version: 0.4.4
setting:
  allowRegister: "N"
notification:
  mail:
    server: ''
    port: ''
    senderEmail: ''
    senderIdentity: ''
    smtp:
      user: ''
      password: ''