export declare const databaseDefaults: Database[];
export declare const getDatabaseDefaultByDataSource: (dataSource: DatabaseDataSource) => Database | undefined;
export declare const getColumnStatus: (column: DatabaseColumn, originalTable?: DatabaseTable) => DatabaseTableItemStatus | undefined;
export declare const getIndexStatus: (index: DatabaseIndex, originalTable?: DatabaseTable) => DatabaseTableItemStatus | undefined;
export declare const isValidTable: (table?: DatabaseTable) => boolean;
export declare const getDefaultIndexName: (table: DatabaseTable, columns: DatabaseIndexColumn[]) => string;
export declare const isDefaultIndexName: (table: DatabaseTable, index: DatabaseIndex) => boolean;
export declare const canColumnAutoIncrement: (column: DatabaseColumn) => false | RegExpMatchArray | null | undefined;
export declare const getDataType: (type: string) => DatabaseDataType;
export declare const normalizeDataType: (value: any, type: string) => any;
export declare const SQL_KEYWORDS: string[];
export declare const MONGO_KEYWORDS: string[];
export declare const getTableManipulationStatementsByDataSource: (dataSource: DatabaseDataSource, tableName?: string) => DatabaseTableManipulationStatements;
export declare const getDatabaseSyntaxKeywordRegexByDataSource: (dataSource: DatabaseDataSource) => DatabaseSyntaxKeywordRegex;
export declare const getDatabaseEditorLanguage: (dataSource: DatabaseDataSource) => string;
export declare const getDatabaseSyntaxKeywords: (dataSource: DatabaseDataSource) => string[];
export declare const getDatabaseAllMetricGroups: () => MetricGroup<DatabaseMetric>[];
export declare const getDatabaseName: (database: Database) => string | undefined;
