apiVersion: v1
kind: Service
metadata:
  name: crawlab
  namespace: crawlab
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
  selector:
    app: crawlab-master
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlab-master
  namespace: crawlab
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawlab-master
  template:
    metadata:
      labels:
        app: crawlab-master
    spec:
      containers:
      - image: tikazyq/crawlab:latest
        imagePullPolicy: Always
        name: crawlab
        env:
        - name: CRAWLAB_SERVER_MASTER
          value: "Y"
        - name: CRAWLAB_MONGO_HOST
          value: "mongo"
        - name: CRAWLAB_REDIS_ADDRESS
          value: "redis"
        # - name: CRAWLAB_SERVER_LANG_NODE
        #   value: "Y"
        # - name: CRAWLAB_SERVER_LANG_JAVA
        #   value: "Y"
        ports:
        - containerPort: 8080
          name: crawlab
