import type { FilterNodeMethodFunction, TreeNodeData } from 'element-plus/es/components/tree/src/tree.type';
type __VLS_Props = {
    tabName: string;
};
declare const _default: import("vue").DefineComponent<__VLS_Props, {
    treeRef: import("vue").Ref<import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("vue").ExtractPropTypes<{
        data: {
            type: ArrayConstructor;
            default: () => never[];
        };
        emptyText: {
            type: StringConstructor;
        };
        renderAfterExpand: {
            type: BooleanConstructor;
            default: boolean;
        };
        nodeKey: StringConstructor;
        checkStrictly: BooleanConstructor;
        defaultExpandAll: BooleanConstructor;
        expandOnClickNode: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkOnClickNode: BooleanConstructor;
        checkOnClickLeaf: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkDescendants: {
            type: BooleanConstructor;
            default: boolean;
        };
        autoExpandParent: {
            type: BooleanConstructor;
            default: boolean;
        };
        defaultCheckedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultCheckedKeys"]>;
        defaultExpandedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultExpandedKeys"]>;
        currentNodeKey: import("vue").PropType<string | number>;
        renderContent: FunctionConstructor;
        showCheckbox: {
            type: BooleanConstructor;
            default: boolean;
        };
        draggable: {
            type: BooleanConstructor;
            default: boolean;
        };
        allowDrag: FunctionConstructor;
        allowDrop: FunctionConstructor;
        props: {
            type: import("vue").PropType<import("element-plus").TreeComponentProps["props"]>;
            default: () => {
                children: string;
                label: string;
                disabled: string;
            };
        };
        lazy: {
            type: BooleanConstructor;
            default: boolean;
        };
        highlightCurrent: BooleanConstructor;
        load: import("vue").PropType<import("element-plus").TreeComponentProps["load"]>;
        filterNodeMethod: import("vue").PropType<import("element-plus").TreeComponentProps["filterNodeMethod"]>;
        accordion: BooleanConstructor;
        indent: {
            type: NumberConstructor;
            default: number;
        };
        icon: {
            type: import("vue").PropType<string | import("vue").Component>;
        };
    }>> & {
        "onCurrent-change"?: ((...args: any[]) => any) | undefined;
        "onNode-expand"?: ((...args: any[]) => any) | undefined;
        onCheck?: ((...args: any[]) => any) | undefined;
        "onCheck-change"?: ((...args: any[]) => any) | undefined;
        "onNode-click"?: ((...args: any[]) => any) | undefined;
        "onNode-contextmenu"?: ((...args: any[]) => any) | undefined;
        "onNode-collapse"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-start"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-end"?: ((...args: any[]) => any) | undefined;
        "onNode-drop"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-leave"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-enter"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-over"?: ((...args: any[]) => any) | undefined;
    }, {
        ns: {
            namespace: import("vue").ComputedRef<string>;
            b: (blockSuffix?: string) => string;
            e: (element?: string) => string;
            m: (modifier?: string) => string;
            be: (blockSuffix?: string, element?: string) => string;
            em: (element?: string, modifier?: string) => string;
            bm: (blockSuffix?: string, modifier?: string) => string;
            bem: (blockSuffix?: string, element?: string, modifier?: string) => string;
            is: {
                (name: string, state: boolean | undefined): string;
                (name: string): string;
            };
            cssVar: (object: Record<string, string>) => Record<string, string>;
            cssVarName: (name: string) => string;
            cssVarBlock: (object: Record<string, string>) => Record<string, string>;
            cssVarBlockName: (name: string) => string;
        };
        store: import("vue").Ref<{
            currentNode: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            currentNodeKey: import("element-plus").TreeKey;
            nodesMap: import("element-plus").TreeStoreNodesMap;
            root: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            data: TreeNodeData[];
            lazy: boolean;
            load: import("element-plus").LoadFunction;
            filterNodeMethod: import("element-plus/es/components/tree/src/tree.type").FilterNodeMethodFunction;
            key: import("element-plus").TreeKey;
            defaultCheckedKeys: import("element-plus").TreeKey[];
            checkStrictly: boolean;
            defaultExpandedKeys: import("element-plus").TreeKey[];
            autoExpandParent: boolean;
            defaultExpandAll: boolean;
            checkDescendants: boolean;
            props: {
                children?: string | undefined;
                label?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string)) | undefined;
                disabled?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                isLeaf?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                class?: ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string | {
                    [key: string]: boolean;
                }) | undefined;
            };
            initialize: () => void;
            filter: (value: import("element-plus").FilterValue) => void;
            setData: (newVal: import("element-plus").TreeData) => void;
            getNode: (data: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => import("element-plus/es/components/tree/src/model/node").default;
            insertBefore: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            append: (data: TreeNodeData, parentData: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
            _initDefaultCheckedNodes: () => void;
            _initDefaultCheckedNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            setDefaultCheckedKey: (newVal: import("element-plus").TreeKey[]) => void;
            registerNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            deregisterNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
            getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
            getHalfCheckedNodes: () => TreeNodeData[];
            getHalfCheckedKeys: () => import("element-plus").TreeKey[];
            _getAllNodes: () => import("element-plus/es/components/tree/src/model/node").default[];
            updateChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
            _setCheckedKeys: (key: import("element-plus").TreeKey, leafOnly: boolean | undefined, checkedKeys: {
                [key: string]: boolean;
            }) => void;
            setCheckedNodes: (array: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
            setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
            setDefaultExpandedKeys: (keys: import("element-plus").TreeKey[]) => void;
            setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
            getCurrentNode: () => import("element-plus/es/components/tree/src/model/node").default;
            setCurrentNode: (currentNode: import("element-plus/es/components/tree/src/model/node").default) => void;
            setUserCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
            setCurrentNodeKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        }>;
        root: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        currentNode: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        dragState: import("vue").Ref<{
            showDropIndicator: boolean;
            draggingNode: null;
            dropNode: null;
            allowDrop: boolean;
            dropType: null;
        }>;
        el$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        dropIndicator$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        isEmpty: import("vue").ComputedRef<boolean>;
        filter: (value: any) => void;
        getNodeKey: (node: import("element-plus/es/components/tree/src/model/node").default) => any;
        getNodePath: (data: import("element-plus").TreeKey | TreeNodeData) => TreeNodeData[];
        getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
        getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
        getCurrentNode: () => TreeNodeData;
        getCurrentKey: () => any;
        setCheckedNodes: (nodes: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
        setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
        setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
        getHalfCheckedNodes: () => TreeNodeData[];
        getHalfCheckedKeys: () => import("element-plus").TreeKey[];
        setCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
        setCurrentKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        t: import("element-plus").Translator;
        getNode: (data: import("element-plus").TreeKey | TreeNodeData) => import("element-plus/es/components/tree/src/model/node").default;
        remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        append: (data: TreeNodeData, parentNode: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertBefore: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertAfter: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        handleNodeExpand: (nodeData: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default, instance: import("vue").ComponentInternalInstance) => void;
        updateKeyChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
    }, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, ("current-change" | "check" | "node-expand" | "check-change" | "node-click" | "node-contextmenu" | "node-collapse" | "node-drag-start" | "node-drag-end" | "node-drop" | "node-drag-leave" | "node-drag-enter" | "node-drag-over")[], import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, {
        data: unknown[];
        props: import("element-plus").TreeOptionProps;
        checkStrictly: boolean;
        lazy: boolean;
        accordion: boolean;
        draggable: boolean;
        defaultExpandAll: boolean;
        indent: number;
        renderAfterExpand: boolean;
        showCheckbox: boolean;
        expandOnClickNode: boolean;
        checkOnClickNode: boolean;
        checkOnClickLeaf: boolean;
        checkDescendants: boolean;
        autoExpandParent: boolean;
        highlightCurrent: boolean;
    }, true, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
        P: {};
        B: {};
        D: {};
        C: {};
        M: {};
        Defaults: {};
    }, Readonly<import("vue").ExtractPropTypes<{
        data: {
            type: ArrayConstructor;
            default: () => never[];
        };
        emptyText: {
            type: StringConstructor;
        };
        renderAfterExpand: {
            type: BooleanConstructor;
            default: boolean;
        };
        nodeKey: StringConstructor;
        checkStrictly: BooleanConstructor;
        defaultExpandAll: BooleanConstructor;
        expandOnClickNode: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkOnClickNode: BooleanConstructor;
        checkOnClickLeaf: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkDescendants: {
            type: BooleanConstructor;
            default: boolean;
        };
        autoExpandParent: {
            type: BooleanConstructor;
            default: boolean;
        };
        defaultCheckedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultCheckedKeys"]>;
        defaultExpandedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultExpandedKeys"]>;
        currentNodeKey: import("vue").PropType<string | number>;
        renderContent: FunctionConstructor;
        showCheckbox: {
            type: BooleanConstructor;
            default: boolean;
        };
        draggable: {
            type: BooleanConstructor;
            default: boolean;
        };
        allowDrag: FunctionConstructor;
        allowDrop: FunctionConstructor;
        props: {
            type: import("vue").PropType<import("element-plus").TreeComponentProps["props"]>;
            default: () => {
                children: string;
                label: string;
                disabled: string;
            };
        };
        lazy: {
            type: BooleanConstructor;
            default: boolean;
        };
        highlightCurrent: BooleanConstructor;
        load: import("vue").PropType<import("element-plus").TreeComponentProps["load"]>;
        filterNodeMethod: import("vue").PropType<import("element-plus").TreeComponentProps["filterNodeMethod"]>;
        accordion: BooleanConstructor;
        indent: {
            type: NumberConstructor;
            default: number;
        };
        icon: {
            type: import("vue").PropType<string | import("vue").Component>;
        };
    }>> & {
        "onCurrent-change"?: ((...args: any[]) => any) | undefined;
        "onNode-expand"?: ((...args: any[]) => any) | undefined;
        onCheck?: ((...args: any[]) => any) | undefined;
        "onCheck-change"?: ((...args: any[]) => any) | undefined;
        "onNode-click"?: ((...args: any[]) => any) | undefined;
        "onNode-contextmenu"?: ((...args: any[]) => any) | undefined;
        "onNode-collapse"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-start"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-end"?: ((...args: any[]) => any) | undefined;
        "onNode-drop"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-leave"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-enter"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-over"?: ((...args: any[]) => any) | undefined;
    }, {
        ns: {
            namespace: import("vue").ComputedRef<string>;
            b: (blockSuffix?: string) => string;
            e: (element?: string) => string;
            m: (modifier?: string) => string;
            be: (blockSuffix?: string, element?: string) => string;
            em: (element?: string, modifier?: string) => string;
            bm: (blockSuffix?: string, modifier?: string) => string;
            bem: (blockSuffix?: string, element?: string, modifier?: string) => string;
            is: {
                (name: string, state: boolean | undefined): string;
                (name: string): string;
            };
            cssVar: (object: Record<string, string>) => Record<string, string>;
            cssVarName: (name: string) => string;
            cssVarBlock: (object: Record<string, string>) => Record<string, string>;
            cssVarBlockName: (name: string) => string;
        };
        store: import("vue").Ref<{
            currentNode: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            currentNodeKey: import("element-plus").TreeKey;
            nodesMap: import("element-plus").TreeStoreNodesMap;
            root: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            data: TreeNodeData[];
            lazy: boolean;
            load: import("element-plus").LoadFunction;
            filterNodeMethod: import("element-plus/es/components/tree/src/tree.type").FilterNodeMethodFunction;
            key: import("element-plus").TreeKey;
            defaultCheckedKeys: import("element-plus").TreeKey[];
            checkStrictly: boolean;
            defaultExpandedKeys: import("element-plus").TreeKey[];
            autoExpandParent: boolean;
            defaultExpandAll: boolean;
            checkDescendants: boolean;
            props: {
                children?: string | undefined;
                label?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string)) | undefined;
                disabled?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                isLeaf?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                class?: ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string | {
                    [key: string]: boolean;
                }) | undefined;
            };
            initialize: () => void;
            filter: (value: import("element-plus").FilterValue) => void;
            setData: (newVal: import("element-plus").TreeData) => void;
            getNode: (data: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => import("element-plus/es/components/tree/src/model/node").default;
            insertBefore: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            append: (data: TreeNodeData, parentData: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
            _initDefaultCheckedNodes: () => void;
            _initDefaultCheckedNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            setDefaultCheckedKey: (newVal: import("element-plus").TreeKey[]) => void;
            registerNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            deregisterNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
            getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
            getHalfCheckedNodes: () => TreeNodeData[];
            getHalfCheckedKeys: () => import("element-plus").TreeKey[];
            _getAllNodes: () => import("element-plus/es/components/tree/src/model/node").default[];
            updateChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
            _setCheckedKeys: (key: import("element-plus").TreeKey, leafOnly: boolean | undefined, checkedKeys: {
                [key: string]: boolean;
            }) => void;
            setCheckedNodes: (array: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
            setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
            setDefaultExpandedKeys: (keys: import("element-plus").TreeKey[]) => void;
            setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
            getCurrentNode: () => import("element-plus/es/components/tree/src/model/node").default;
            setCurrentNode: (currentNode: import("element-plus/es/components/tree/src/model/node").default) => void;
            setUserCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
            setCurrentNodeKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        }>;
        root: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        currentNode: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        dragState: import("vue").Ref<{
            showDropIndicator: boolean;
            draggingNode: null;
            dropNode: null;
            allowDrop: boolean;
            dropType: null;
        }>;
        el$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        dropIndicator$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        isEmpty: import("vue").ComputedRef<boolean>;
        filter: (value: any) => void;
        getNodeKey: (node: import("element-plus/es/components/tree/src/model/node").default) => any;
        getNodePath: (data: import("element-plus").TreeKey | TreeNodeData) => TreeNodeData[];
        getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
        getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
        getCurrentNode: () => TreeNodeData;
        getCurrentKey: () => any;
        setCheckedNodes: (nodes: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
        setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
        setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
        getHalfCheckedNodes: () => TreeNodeData[];
        getHalfCheckedKeys: () => import("element-plus").TreeKey[];
        setCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
        setCurrentKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        t: import("element-plus").Translator;
        getNode: (data: import("element-plus").TreeKey | TreeNodeData) => import("element-plus/es/components/tree/src/model/node").default;
        remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        append: (data: TreeNodeData, parentNode: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertBefore: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertAfter: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        handleNodeExpand: (nodeData: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default, instance: import("vue").ComponentInternalInstance) => void;
        updateKeyChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
    }, {}, {}, {}, {
        data: unknown[];
        props: import("element-plus").TreeOptionProps;
        checkStrictly: boolean;
        lazy: boolean;
        accordion: boolean;
        draggable: boolean;
        defaultExpandAll: boolean;
        indent: number;
        renderAfterExpand: boolean;
        showCheckbox: boolean;
        expandOnClickNode: boolean;
        checkOnClickNode: boolean;
        checkOnClickLeaf: boolean;
        checkDescendants: boolean;
        autoExpandParent: boolean;
        highlightCurrent: boolean;
    }> | undefined, import("vue").CreateComponentPublicInstanceWithMixins<Readonly<import("vue").ExtractPropTypes<{
        data: {
            type: ArrayConstructor;
            default: () => never[];
        };
        emptyText: {
            type: StringConstructor;
        };
        renderAfterExpand: {
            type: BooleanConstructor;
            default: boolean;
        };
        nodeKey: StringConstructor;
        checkStrictly: BooleanConstructor;
        defaultExpandAll: BooleanConstructor;
        expandOnClickNode: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkOnClickNode: BooleanConstructor;
        checkOnClickLeaf: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkDescendants: {
            type: BooleanConstructor;
            default: boolean;
        };
        autoExpandParent: {
            type: BooleanConstructor;
            default: boolean;
        };
        defaultCheckedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultCheckedKeys"]>;
        defaultExpandedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultExpandedKeys"]>;
        currentNodeKey: import("vue").PropType<string | number>;
        renderContent: FunctionConstructor;
        showCheckbox: {
            type: BooleanConstructor;
            default: boolean;
        };
        draggable: {
            type: BooleanConstructor;
            default: boolean;
        };
        allowDrag: FunctionConstructor;
        allowDrop: FunctionConstructor;
        props: {
            type: import("vue").PropType<import("element-plus").TreeComponentProps["props"]>;
            default: () => {
                children: string;
                label: string;
                disabled: string;
            };
        };
        lazy: {
            type: BooleanConstructor;
            default: boolean;
        };
        highlightCurrent: BooleanConstructor;
        load: import("vue").PropType<import("element-plus").TreeComponentProps["load"]>;
        filterNodeMethod: import("vue").PropType<import("element-plus").TreeComponentProps["filterNodeMethod"]>;
        accordion: BooleanConstructor;
        indent: {
            type: NumberConstructor;
            default: number;
        };
        icon: {
            type: import("vue").PropType<string | import("vue").Component>;
        };
    }>> & {
        "onCurrent-change"?: ((...args: any[]) => any) | undefined;
        "onNode-expand"?: ((...args: any[]) => any) | undefined;
        onCheck?: ((...args: any[]) => any) | undefined;
        "onCheck-change"?: ((...args: any[]) => any) | undefined;
        "onNode-click"?: ((...args: any[]) => any) | undefined;
        "onNode-contextmenu"?: ((...args: any[]) => any) | undefined;
        "onNode-collapse"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-start"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-end"?: ((...args: any[]) => any) | undefined;
        "onNode-drop"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-leave"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-enter"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-over"?: ((...args: any[]) => any) | undefined;
    }, {
        ns: {
            namespace: import("vue").ComputedRef<string>;
            b: (blockSuffix?: string) => string;
            e: (element?: string) => string;
            m: (modifier?: string) => string;
            be: (blockSuffix?: string, element?: string) => string;
            em: (element?: string, modifier?: string) => string;
            bm: (blockSuffix?: string, modifier?: string) => string;
            bem: (blockSuffix?: string, element?: string, modifier?: string) => string;
            is: {
                (name: string, state: boolean | undefined): string;
                (name: string): string;
            };
            cssVar: (object: Record<string, string>) => Record<string, string>;
            cssVarName: (name: string) => string;
            cssVarBlock: (object: Record<string, string>) => Record<string, string>;
            cssVarBlockName: (name: string) => string;
        };
        store: import("vue").Ref<{
            currentNode: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            currentNodeKey: import("element-plus").TreeKey;
            nodesMap: import("element-plus").TreeStoreNodesMap;
            root: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            data: TreeNodeData[];
            lazy: boolean;
            load: import("element-plus").LoadFunction;
            filterNodeMethod: import("element-plus/es/components/tree/src/tree.type").FilterNodeMethodFunction;
            key: import("element-plus").TreeKey;
            defaultCheckedKeys: import("element-plus").TreeKey[];
            checkStrictly: boolean;
            defaultExpandedKeys: import("element-plus").TreeKey[];
            autoExpandParent: boolean;
            defaultExpandAll: boolean;
            checkDescendants: boolean;
            props: {
                children?: string | undefined;
                label?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string)) | undefined;
                disabled?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                isLeaf?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                class?: ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string | {
                    [key: string]: boolean;
                }) | undefined;
            };
            initialize: () => void;
            filter: (value: import("element-plus").FilterValue) => void;
            setData: (newVal: import("element-plus").TreeData) => void;
            getNode: (data: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => import("element-plus/es/components/tree/src/model/node").default;
            insertBefore: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            append: (data: TreeNodeData, parentData: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
            _initDefaultCheckedNodes: () => void;
            _initDefaultCheckedNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            setDefaultCheckedKey: (newVal: import("element-plus").TreeKey[]) => void;
            registerNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            deregisterNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
            getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
            getHalfCheckedNodes: () => TreeNodeData[];
            getHalfCheckedKeys: () => import("element-plus").TreeKey[];
            _getAllNodes: () => import("element-plus/es/components/tree/src/model/node").default[];
            updateChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
            _setCheckedKeys: (key: import("element-plus").TreeKey, leafOnly: boolean | undefined, checkedKeys: {
                [key: string]: boolean;
            }) => void;
            setCheckedNodes: (array: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
            setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
            setDefaultExpandedKeys: (keys: import("element-plus").TreeKey[]) => void;
            setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
            getCurrentNode: () => import("element-plus/es/components/tree/src/model/node").default;
            setCurrentNode: (currentNode: import("element-plus/es/components/tree/src/model/node").default) => void;
            setUserCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
            setCurrentNodeKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        }>;
        root: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        currentNode: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        dragState: import("vue").Ref<{
            showDropIndicator: boolean;
            draggingNode: null;
            dropNode: null;
            allowDrop: boolean;
            dropType: null;
        }>;
        el$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        dropIndicator$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        isEmpty: import("vue").ComputedRef<boolean>;
        filter: (value: any) => void;
        getNodeKey: (node: import("element-plus/es/components/tree/src/model/node").default) => any;
        getNodePath: (data: import("element-plus").TreeKey | TreeNodeData) => TreeNodeData[];
        getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
        getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
        getCurrentNode: () => TreeNodeData;
        getCurrentKey: () => any;
        setCheckedNodes: (nodes: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
        setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
        setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
        getHalfCheckedNodes: () => TreeNodeData[];
        getHalfCheckedKeys: () => import("element-plus").TreeKey[];
        setCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
        setCurrentKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        t: import("element-plus").Translator;
        getNode: (data: import("element-plus").TreeKey | TreeNodeData) => import("element-plus/es/components/tree/src/model/node").default;
        remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        append: (data: TreeNodeData, parentNode: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertBefore: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertAfter: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        handleNodeExpand: (nodeData: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default, instance: import("vue").ComponentInternalInstance) => void;
        updateKeyChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
    }, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, ("current-change" | "check" | "node-expand" | "check-change" | "node-click" | "node-contextmenu" | "node-collapse" | "node-drag-start" | "node-drag-end" | "node-drop" | "node-drag-leave" | "node-drag-enter" | "node-drag-over")[], import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, {
        data: unknown[];
        props: import("element-plus").TreeOptionProps;
        checkStrictly: boolean;
        lazy: boolean;
        accordion: boolean;
        draggable: boolean;
        defaultExpandAll: boolean;
        indent: number;
        renderAfterExpand: boolean;
        showCheckbox: boolean;
        expandOnClickNode: boolean;
        checkOnClickNode: boolean;
        checkOnClickLeaf: boolean;
        checkDescendants: boolean;
        autoExpandParent: boolean;
        highlightCurrent: boolean;
    }, true, {}, {}, import("vue").GlobalComponents, import("vue").GlobalDirectives, string, {}, any, import("vue").ComponentProvideOptions, {
        P: {};
        B: {};
        D: {};
        C: {};
        M: {};
        Defaults: {};
    }, Readonly<import("vue").ExtractPropTypes<{
        data: {
            type: ArrayConstructor;
            default: () => never[];
        };
        emptyText: {
            type: StringConstructor;
        };
        renderAfterExpand: {
            type: BooleanConstructor;
            default: boolean;
        };
        nodeKey: StringConstructor;
        checkStrictly: BooleanConstructor;
        defaultExpandAll: BooleanConstructor;
        expandOnClickNode: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkOnClickNode: BooleanConstructor;
        checkOnClickLeaf: {
            type: BooleanConstructor;
            default: boolean;
        };
        checkDescendants: {
            type: BooleanConstructor;
            default: boolean;
        };
        autoExpandParent: {
            type: BooleanConstructor;
            default: boolean;
        };
        defaultCheckedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultCheckedKeys"]>;
        defaultExpandedKeys: import("vue").PropType<import("element-plus").TreeComponentProps["defaultExpandedKeys"]>;
        currentNodeKey: import("vue").PropType<string | number>;
        renderContent: FunctionConstructor;
        showCheckbox: {
            type: BooleanConstructor;
            default: boolean;
        };
        draggable: {
            type: BooleanConstructor;
            default: boolean;
        };
        allowDrag: FunctionConstructor;
        allowDrop: FunctionConstructor;
        props: {
            type: import("vue").PropType<import("element-plus").TreeComponentProps["props"]>;
            default: () => {
                children: string;
                label: string;
                disabled: string;
            };
        };
        lazy: {
            type: BooleanConstructor;
            default: boolean;
        };
        highlightCurrent: BooleanConstructor;
        load: import("vue").PropType<import("element-plus").TreeComponentProps["load"]>;
        filterNodeMethod: import("vue").PropType<import("element-plus").TreeComponentProps["filterNodeMethod"]>;
        accordion: BooleanConstructor;
        indent: {
            type: NumberConstructor;
            default: number;
        };
        icon: {
            type: import("vue").PropType<string | import("vue").Component>;
        };
    }>> & {
        "onCurrent-change"?: ((...args: any[]) => any) | undefined;
        "onNode-expand"?: ((...args: any[]) => any) | undefined;
        onCheck?: ((...args: any[]) => any) | undefined;
        "onCheck-change"?: ((...args: any[]) => any) | undefined;
        "onNode-click"?: ((...args: any[]) => any) | undefined;
        "onNode-contextmenu"?: ((...args: any[]) => any) | undefined;
        "onNode-collapse"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-start"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-end"?: ((...args: any[]) => any) | undefined;
        "onNode-drop"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-leave"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-enter"?: ((...args: any[]) => any) | undefined;
        "onNode-drag-over"?: ((...args: any[]) => any) | undefined;
    }, {
        ns: {
            namespace: import("vue").ComputedRef<string>;
            b: (blockSuffix?: string) => string;
            e: (element?: string) => string;
            m: (modifier?: string) => string;
            be: (blockSuffix?: string, element?: string) => string;
            em: (element?: string, modifier?: string) => string;
            bm: (blockSuffix?: string, modifier?: string) => string;
            bem: (blockSuffix?: string, element?: string, modifier?: string) => string;
            is: {
                (name: string, state: boolean | undefined): string;
                (name: string): string;
            };
            cssVar: (object: Record<string, string>) => Record<string, string>;
            cssVarName: (name: string) => string;
            cssVarBlock: (object: Record<string, string>) => Record<string, string>;
            cssVarBlockName: (name: string) => string;
        };
        store: import("vue").Ref<{
            currentNode: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            currentNodeKey: import("element-plus").TreeKey;
            nodesMap: import("element-plus").TreeStoreNodesMap;
            root: {
                id: number;
                text: string;
                checked: boolean;
                indeterminate: boolean;
                data: TreeNodeData;
                expanded: boolean;
                parent: any;
                visible: boolean;
                isCurrent: boolean;
                store: any;
                isLeafByUser: boolean;
                isLeaf: boolean;
                canFocus: boolean;
                level: number;
                loaded: boolean;
                childNodes: any[];
                loading: boolean;
                initialize: () => void;
                setData: (data: TreeNodeData) => void;
                readonly label: string;
                readonly key: import("element-plus").TreeKey;
                readonly disabled: boolean;
                readonly nextSibling: any | null;
                readonly previousSibling: any | null;
                contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
                remove: () => void;
                insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
                insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
                removeChildByData: (data: TreeNodeData) => void;
                expand: (callback?: () => void, expandParent?: boolean) => void;
                doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                collapse: () => void;
                shouldLoadData: () => boolean;
                updateLeafState: () => void;
                setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
                getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
                updateChildren: () => void;
                loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
                eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
                reInitChecked: () => void;
            };
            data: TreeNodeData[];
            lazy: boolean;
            load: import("element-plus").LoadFunction;
            filterNodeMethod: import("element-plus/es/components/tree/src/tree.type").FilterNodeMethodFunction;
            key: import("element-plus").TreeKey;
            defaultCheckedKeys: import("element-plus").TreeKey[];
            checkStrictly: boolean;
            defaultExpandedKeys: import("element-plus").TreeKey[];
            autoExpandParent: boolean;
            defaultExpandAll: boolean;
            checkDescendants: boolean;
            props: {
                children?: string | undefined;
                label?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string)) | undefined;
                disabled?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                isLeaf?: (string | ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => boolean)) | undefined;
                class?: ((data: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default) => string | {
                    [key: string]: boolean;
                }) | undefined;
            };
            initialize: () => void;
            filter: (value: import("element-plus").FilterValue) => void;
            setData: (newVal: import("element-plus").TreeData) => void;
            getNode: (data: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => import("element-plus/es/components/tree/src/model/node").default;
            insertBefore: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (data: TreeNodeData, refData: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
            append: (data: TreeNodeData, parentData: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
            _initDefaultCheckedNodes: () => void;
            _initDefaultCheckedNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            setDefaultCheckedKey: (newVal: import("element-plus").TreeKey[]) => void;
            registerNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            deregisterNode: (node: import("element-plus/es/components/tree/src/model/node").default) => void;
            getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
            getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
            getHalfCheckedNodes: () => TreeNodeData[];
            getHalfCheckedKeys: () => import("element-plus").TreeKey[];
            _getAllNodes: () => import("element-plus/es/components/tree/src/model/node").default[];
            updateChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
            _setCheckedKeys: (key: import("element-plus").TreeKey, leafOnly: boolean | undefined, checkedKeys: {
                [key: string]: boolean;
            }) => void;
            setCheckedNodes: (array: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
            setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
            setDefaultExpandedKeys: (keys: import("element-plus").TreeKey[]) => void;
            setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
            getCurrentNode: () => import("element-plus/es/components/tree/src/model/node").default;
            setCurrentNode: (currentNode: import("element-plus/es/components/tree/src/model/node").default) => void;
            setUserCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
            setCurrentNodeKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        }>;
        root: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        currentNode: import("vue").Ref<{
            id: number;
            text: string;
            checked: boolean;
            indeterminate: boolean;
            data: TreeNodeData;
            expanded: boolean;
            parent: any;
            visible: boolean;
            isCurrent: boolean;
            store: any;
            isLeafByUser: boolean;
            isLeaf: boolean;
            canFocus: boolean;
            level: number;
            loaded: boolean;
            childNodes: any[];
            loading: boolean;
            initialize: () => void;
            setData: (data: TreeNodeData) => void;
            readonly label: string;
            readonly key: import("element-plus").TreeKey;
            readonly disabled: boolean;
            readonly nextSibling: any | null;
            readonly previousSibling: any | null;
            contains: (target: import("element-plus/es/components/tree/src/model/node").default, deep?: boolean) => boolean;
            remove: () => void;
            insertChild: (child?: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, index?: number, batch?: boolean) => void;
            insertBefore: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            insertAfter: (child: import("element-plus").FakeNode | import("element-plus/es/components/tree/src/model/node").default, ref: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChild: (child: import("element-plus/es/components/tree/src/model/node").default) => void;
            removeChildByData: (data: TreeNodeData) => void;
            expand: (callback?: () => void, expandParent?: boolean) => void;
            doCreateChildren: (array: TreeNodeData[], defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            collapse: () => void;
            shouldLoadData: () => boolean;
            updateLeafState: () => void;
            setChecked: (value?: boolean | string, deep?: boolean, recursion?: boolean, passValue?: boolean) => void;
            getChildren: (forceInit?: boolean) => TreeNodeData | TreeNodeData[];
            updateChildren: () => void;
            loadData: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void, defaultProps?: import("element-plus").TreeNodeLoadedDefaultProps) => void;
            eachNode: (callback: (node: import("element-plus/es/components/tree/src/model/node").default) => void) => void;
            reInitChecked: () => void;
        }>;
        dragState: import("vue").Ref<{
            showDropIndicator: boolean;
            draggingNode: null;
            dropNode: null;
            allowDrop: boolean;
            dropType: null;
        }>;
        el$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        dropIndicator$: import("vue").Ref<import("element-plus/es/utils").Nullable<HTMLElement>>;
        isEmpty: import("vue").ComputedRef<boolean>;
        filter: (value: any) => void;
        getNodeKey: (node: import("element-plus/es/components/tree/src/model/node").default) => any;
        getNodePath: (data: import("element-plus").TreeKey | TreeNodeData) => TreeNodeData[];
        getCheckedNodes: (leafOnly?: boolean, includeHalfChecked?: boolean) => TreeNodeData[];
        getCheckedKeys: (leafOnly?: boolean) => import("element-plus").TreeKey[];
        getCurrentNode: () => TreeNodeData;
        getCurrentKey: () => any;
        setCheckedNodes: (nodes: import("element-plus/es/components/tree/src/model/node").default[], leafOnly?: boolean) => void;
        setCheckedKeys: (keys: import("element-plus").TreeKey[], leafOnly?: boolean) => void;
        setChecked: (data: import("element-plus").TreeKey | TreeNodeData, checked: boolean, deep: boolean) => void;
        getHalfCheckedNodes: () => TreeNodeData[];
        getHalfCheckedKeys: () => import("element-plus").TreeKey[];
        setCurrentNode: (node: import("element-plus/es/components/tree/src/model/node").default, shouldAutoExpandParent?: boolean) => void;
        setCurrentKey: (key?: import("element-plus").TreeKey, shouldAutoExpandParent?: boolean) => void;
        t: import("element-plus").Translator;
        getNode: (data: import("element-plus").TreeKey | TreeNodeData) => import("element-plus/es/components/tree/src/model/node").default;
        remove: (data: TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        append: (data: TreeNodeData, parentNode: TreeNodeData | import("element-plus").TreeKey | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertBefore: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        insertAfter: (data: TreeNodeData, refNode: import("element-plus").TreeKey | TreeNodeData | import("element-plus/es/components/tree/src/model/node").default) => void;
        handleNodeExpand: (nodeData: TreeNodeData, node: import("element-plus/es/components/tree/src/model/node").default, instance: import("vue").ComponentInternalInstance) => void;
        updateKeyChildren: (key: import("element-plus").TreeKey, data: import("element-plus").TreeData) => void;
    }, {}, {}, {}, {
        data: unknown[];
        props: import("element-plus").TreeOptionProps;
        checkStrictly: boolean;
        lazy: boolean;
        accordion: boolean;
        draggable: boolean;
        defaultExpandAll: boolean;
        indent: number;
        renderAfterExpand: boolean;
        showCheckbox: boolean;
        expandOnClickNode: boolean;
        checkOnClickNode: boolean;
        checkOnClickLeaf: boolean;
        checkDescendants: boolean;
        autoExpandParent: boolean;
        highlightCurrent: boolean;
    }> | undefined>;
    selectNode: (data: DatabaseNavItem, tabName?: string) => Promise<void>;
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<__VLS_Props> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
export default _default;
