import { CellStyle } from 'element-plus';
declare const useDependencyList: () => {
    config: import("vue").ComputedRef<DependencyConfig | undefined>;
    lang: import("vue").ComputedRef<DependencyLang>;
    tableLoading: import("vue").ComputedRef<boolean>;
    tableColumns: import("vue").ComputedRef<TableColumns<DependencyRepo>>;
    tableData: import("vue").ComputedRef<TableData<DependencyRepo> | TableData<DependencyConfigSetup>>;
    tableTotal: import("vue").ComputedRef<number>;
    tablePagination: import("vue").ComputedRef<TablePagination>;
    tableCellStyle: import("vue").ComputedRef<CellStyle<any>>;
    actionFunctions: ListLayoutActionFunctions;
    repoTabName: import("vue").ComputedRef<DependencyRepoTabName>;
    repoTabItems: import("vue").ComputedRef<NavItem<any>[]>;
    onClickTableEmptySearch: () => void;
    onClickTableEmptyConfigNotSetup: () => void;
    onClickTableEmptyJava: () => Promise<void>;
    navActions?: import("vue").Ref<ListActionGroup[]>;
    tableListFilter: import("vue").Ref<FilterConditionData[]>;
    tableListSort: import("vue").Ref<SortData[]>;
    activeDialogKey: import("vue").ComputedRef<DialogKey | undefined>;
};
export default useDependencyList;
