version: '3.3'
services:
  master:
    image: ghcr.io/crawlab-team/crawlab:${CRAWLAB_TAG:-develop}
    container_name: crawlab_ghcr_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    image: ghcr.io/crawlab-team/crawlab:${CRAWLAB_TAG:-develop}
    container_name: crawlab_ghcr_worker
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_MASTER_HOST: "master"
    depends_on:
      - master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:5
